importation des librairies

In [49]:
from PIL import Image
import numpy as np

In [50]:
im=Image.open("simpson.png")
im.show()

In [51]:
tableau=np.array(im)
nb_lignes,nb_colonnes,r=tableau.shape
print(nb_lignes,nb_colonnes,r)


626 417 4


In [52]:
print(tableau[0])

[[255 101 165 255]
 [255 101 165 255]
 [255 101 165 255]
 ...
 [ 39  20  13 255]
 [ 38  19  12 255]
 [ 49  29  22 255]]


In [53]:
print(tableau[0][0])

[255 101 165 255]


In [54]:
print(tableau[0][0][0])

255


In [55]:
print(tableau[0][0][1])

101


In [56]:
print(im.format, im.size, im.mode)

PNG (417, 626) RGBA


In [57]:
print(tableau.shape)

(626, 417, 4)


In [58]:
print(tableau[nb_lignes-1][nb_colonnes-1])

[253 230   2 255]


In [66]:
for ligne in range(nb_lignes):
    for colonne in range(nb_colonnes):
        tableau[ligne][colonne][0]=0

new=Image.fromarray(tableau)
new.show()