importation des librairies

In [90]:
from PIL import Image
import numpy as np

In [91]:
im=Image.open("simpson.png")
im.show()

In [92]:
tableau=np.array(im)
nb_lignes,nb_colonnes,r=tableau.shape
print(nb_lignes,nb_colonnes,r)


626 417 4


In [93]:
print(tableau[0])

[[255 101 165 255]
 [255 101 165 255]
 [255 101 165 255]
 ...
 [ 39  20  13 255]
 [ 38  19  12 255]
 [ 49  29  22 255]]


In [94]:
print(tableau[0][0])

[255 101 165 255]


In [95]:
print(tableau[0][0][0])

255


In [96]:
print(tableau[0][0][1])

101


In [97]:
print(im.format, im.size, im.mode)

PNG (417, 626) RGBA


In [98]:
print(tableau.shape)

(626, 417, 4)


In [99]:
print(tableau[nb_lignes-1][nb_colonnes-1])

[253 230   2 255]


In [102]:
tableau1=tableau.copy()
for ligne in range(nb_lignes):
    for colonne in range(nb_colonnes):
        #tableau1[ligne][colonne][0]=0
        tableau1[ligne][colonne][1]=0
        tableau1[ligne][colonne][2]=0

new=Image.fromarray(tableau1)
new.show()

In [103]:
tableau2=tableau.copy()
for ligne in range(nb_lignes):
    tableau2[ligne][205][0]=0
    tableau2[ligne][205][1]=0
    tableau2[ligne][205][2]=0

new=Image.fromarray(tableau2)
new.show()